### ISSUE TITLE
How can I find this file, final_nodeonly_node_data_{graph_used}_v1.csv?

### ISSUE THREAD

**Issue by sunnchioo** [geneDRAGNN/geneDRAGNN#1]
Thanks for your contribution!  But I have some problems of this project.

What is the meaning of `node_data_path = f'data/{graph_used}_graph/final_nodeonly_node_data_{graph_used}_v1.csv'` in code?

How can I get `final_nodeonly_node_data_{graph_used}_v1.csv`?

what `graph_used` represents?

**Comment by ciaranbylesho** [comment]
There was an issue when updating the files to a new file convention system. A new data URL has been uploaded and the broken scripts should have been fixed.

Sorry for the issues!
